# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'NaviApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Mapbox-iOS-SDK', '~> 5.5.1'
  pod 'MapboxNavigation', '~> 0.39.0'
  
  # Pods for NaviApp

  target 'NaviAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NaviAppUITests' do
    # Pods for testing
  end

end
